# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_asignaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignaciones',
            name='descripcion',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
