# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=50)),
                ('permisos_documentos', models.BooleanField()),
                ('permisos_facturas', models.BooleanField()),
                ('permisos_inventarios', models.BooleanField()),
                ('permisos_empleados', models.BooleanField()),
                ('permisos_obras', models.BooleanField()),
            ],
        ),
    ]
