# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='imagen',
            field=models.FileField(null=True, upload_to='documentos/Imagenes/'),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='observacion',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
