# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0004_auto_20171123_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento_contable',
            name='estado',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='documento_ingenieria',
            name='estado',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
