# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 18:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('obra', '0001_initial'),
        ('user', '0003_auto_20171123_1819'),
        ('documentos', '0005_auto_20171123_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento_admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('tipo_doc', models.CharField(max_length=50)),
                ('fecha_carga', models.DateField()),
                ('archivo', models.FileField(upload_to='documentos/DocumentoAdministrador/')),
                ('nro_paginas', models.IntegerField()),
                ('estado', models.CharField(max_length=50, null=True)),
                ('descripcion', models.CharField(max_length=300)),
                ('observacion', models.CharField(max_length=300)),
                ('fk_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Perfil')),
                ('fk_obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='obra.Obra')),
            ],
        ),
    ]
