# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 18:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0006_documento_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento_admin',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='documento_admin',
            name='observacion',
        ),
    ]
