# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='imagen',
            field=models.FileField(upload_to='facturas/Imagenes/'),
        ),
    ]
