# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 01:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Empleado',
            new_name='EmpleadoUser',
        ),
    ]
