# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 01:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obra', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='fechaFin',
            field=models.DateField(null=True),
        ),
    ]
