# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obra', '0002_auto_20171122_0130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='obra',
            old_name='fk_administrador',
            new_name='fk_administrador_id',
        ),
        migrations.AlterField(
            model_name='obra',
            name='imagen',
            field=models.FileField(null=True, upload_to='apps/obra/Imagenes/'),
        ),
    ]
