# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obra', '0003_auto_20171122_0624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='imagen',
            field=models.FileField(null=True, upload_to='obra/Imagenes/'),
        ),
    ]
