# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomina',
            name='archivo',
            field=models.FileField(null=True, upload_to='contabilidad/Documentos/'),
        ),
        migrations.AlterField(
            model_name='nomina',
            name='aux_alimentacion',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='nomina',
            name='retencion_fuente',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
