# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomina',
            name='archivo',
            field=models.FileField(upload_to='contabilidad/Documentos/'),
        ),
    ]
